version: '3.7'
services:
  carousels:
    build: .
    container_name: carousels
    image: libapps-admin.uncw.edu:8000/randall-dev/carousels
    platform: linux/x86_64/v8
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./app/:/usr/src/app/
    command: npm run dev
    restart: always