version: '3.7'
services:
  new-titles:
    build: .
    container_name: new-titles
    ports:
      - "8009:3000"
    env_file: .env
    volumes:
      - ./app/:/usr/src/app/
    command: npm run dev
    # command: npm start
    # command: npm test
    restart: always