version: '2'
services:
  readbox:
    image: libapps-admin.uncw.edu:8000/randall-dev/readbox
    restart: always
    environment:
      SIERRA_USER: ChangeMe!
      SIERRA_PASS: ChangeMe!
      NODE_ENV: production
